name: Build latest image

on:
  schedule:
    - cron: '29 23 * * 3'
  repository_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
      - name: Cache pacman packages
        uses: actions/cache@master
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-x86_64

      - name: Update package database
        run: |
          pacman -Sy

      - name: Install runtime dependencies
        run: |
          pacman -S --noconfirm git pyalpm python

      - uses: actions/checkout@master

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Configure arch4edu
        run: |
          cat pacman.conf >> /etc/pacman.conf

      - name: Update package database again
        run: |
          pacman -Sy
          pacman -Fy

      - name: Generate packages.txt
        run: |
          python packages.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: calilbot
          author_email: calil@jingbei.li
          message: "Updated packages.txt"
          add: "packages.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.CALIL_GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - uses: actions/checkout@master

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Generate Dockerfile
        run: |
          packages=$(grep -v '^#' packages.txt)
          packages=$(echo $packages)
          sed "s/PACKAGES/$packages/" Dockerfile.template > Dockerfile

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: arch4edu/base
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
